### ISSUE TITLE
When passing pkey=True to the executor method it returns factory instead

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/python-rrmngmnt#141]
https://github.com/rhevm-qe-automation/python-rrmngmnt/blob/14ae0c998d062a721bbb01a47df0217cf207f1ae/rrmngmnt/host.py#L233

it should be:

```
            ef = copy.copy(self.executor_factory)
```

and here
https://github.com/rhevm-qe-automation/python-rrmngmnt/blob/14ae0c998d062a721bbb01a47df0217cf207f1ae/rrmngmnt/host.py#L235

there should be

```
            return ef(self.ip, user, self.sudo)
```

**Comment by lukas-bednar** [comment]
cc @mgold1234

**Comment by mgold1234** [comment]
https://github.com/rhevm-qe-automation/python-rrmngmnt/pull/142
