### ISSUE TITLE
Add option to remove packages which matches given pattern

### ISSUE THREAD

**Issue by petr-balogh** [rhevm-qe-automation/python-rrmngmnt#41]
Command which I am using looks like this:
remove_old_repo_cmd = [
            'rpm', '-qa', '\'(abc|drf)*\'', '|', 'xargs', 'rpm',
            '-e'
]

It would be great have this functionality in package_manager.
NOTE it should be encapsulated for all package managers which are covered by this module.

**Comment by lukas-bednar** [comment]
covered by #42

**Comment by lukas-bednar** [comment]
via #57
