### ISSUE TITLE
host.service with RHEL Atomic doesn't find suitable service provider

### ISSUE THREAD

**Issue by KwisatzHaderach** [rhevm-qe-automation/python-rrmngmnt#94]
Using host.service on a RHEL Atomic host doesn't find suitable service provider even though systemd provider should be a match for this.

Service: ovirt-guest-agent

**Comment by myakove** [comment]
On which RHEL atomic version?
I just tried on Red Hat Enterprise Linux Atomic Host release 7.4 and it's worked.
```
ipdb> remote_resource.service('crond').status()
True
```
Is ovirt-guest-agent install, you will get this error 'Exception: Can not find suitable service provider: [<class 'rrmngmnt.service.Systemd'>, <class 'rrmngmnt.service.SysVinit'>, <class 'rrmngmnt.service.InitCtl'>]' if the service is not found.

**Comment by KwisatzHaderach** [comment]
Yeah, sorry, the test was probably too fast for the service I just installed and tried to check.
